core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include(('weather.urls', 'weather'), namespace='weather')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/urls.py
from django.urls import path

from .views import add_weather, weather_list, summary_list, delete_summary


urlpatterns = [
    path('add/', add_weather, name='add-weather'),
    path('list/', weather_list, name='weather-list'),
    path('summary/list/', summary_list, name='summary-list'),
    path('summary/<int:summary_id>/delete/', delete_summary, name='delete-summary'),
] 

weather/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator

from .utils import round_avg


class BaseTimestamp(models.Model):
    """
    Timestamp abstract model to be inherited from.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        abstract = True


class WeatherManager(models.Manager):
    """
    Weather Record model manager.
    """
    def get_avg_temp(self, n=10):
        """
        Take n, and return rounded avgerage temperature of last nth records.
        """
        avg = sum(self.get_queryset().values_list('temp', flat=True)[:n]) / n
        return round_avg(avg, 2)

    def get_avg_humidity(self, n=10):
        """
        Take n, and return rounded avgerage humidity of last nth records.
        """
        avg = sum(self.get_queryset().values_list('humidity', flat=True)[:n]) / n
        return round_avg(avg, 2)

    def get_last_n_dates(self, n=10):
        """
        Take n, and return dates of the last nth records.
        """
        return self.get_queryset().values_list('created_at', flat=True)[:n]

    def set_summary_id(self, summary_id, n=10):
        """
        Take summary's id & n, and set that id to last nth records.
        """
        ids_list = self.get_queryset().values_list('pk', flat=True)[:n]
        return self.get_queryset().filter(pk__in=ids_list).update(summary_id=summary_id)


class Weather(BaseTimestamp):
    """
    Weather Record model.
    """
    temp = models.FloatField("Temperature", validators=[MinValueValidator(19.0), MaxValueValidator(28.0)])
    humidity = models.FloatField(validators=[MinValueValidator(35.0), MaxValueValidator(65.0)])
    summary_id = models.PositiveIntegerField(null=True, blank=True)

    objects = WeatherManager()

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'Weather Records'

    def __str__ (self):
        """Return weather's timestamp & temperature & humidity."""
        return f"{self.id} | {self.date} | {self.time} | T:{self.temp} | H:{self.humidity}"

    @property  
    def date(self):
        """Return a nicely formatted date string, eg: Aug 06, 2020."""
        return self.created_at.strftime("%b %d, %Y")

    @property
    def time(self):
        """Return a nicely formatted time string, eg: 07:21 PM."""
        return self.created_at.strftime("%I:%M %p") 

    def is_temp_gt_25(self):
        """Return true if temp is greater than 25"""
        return self.temp > 25.0

    def is_temp_lte_25(self):
        """Return true if temp is less than or equal 25"""
        return self.temp <= 25.0

    def is_humidity_gt_55(self):
        """Return true if humidity is greater than 55"""
        return self.humidity > 55.0

    def is_humidity_lte_55(self):
        """Return true if humidity is less than or equal 55"""
        return self.humidity <= 55.0

    def get_prev(self):
        """Return previous value of the element."""
        return self.get_previous_by_created_at()

    def is_temp_lt_prev(self):
        """Return true if temp is less than the previous value."""
        return self.temp < self.get_prev().temp 

    def is_temp_gt_prev(self):
        """Return true if temp is greater than the previous value."""
        return self.temp > self.get_prev().temp 

    def is_humidity_lt_prev(self):
        """Return true if humidity is less than the previous value."""
        return self.humidity < self.get_prev().humidity 

    def is_humidity_gt_prev(self):
        """Return true if humidity is greater than the previous value."""
        return self.humidity > self.get_prev().humidity 
           

class Summary(BaseTimestamp):
    """
    Weather Record Summary model.
    """
    avg_temp = models.FloatField("Average Temperature")
    avg_humidity = models.FloatField("Average Humidity")
    start_date = models.DateField("Date of first record of the 10 records")
    end_date = models.DateField("Date of last record of the 10 records")

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'Summaries'

    def __str__ (self):
        """Return summary's start_date & end_date & avg temperature & avg humidity."""
        return f"{self.start_date} | {self.end_date} | T:{self.avg_temp} | H:{self.avg_humidity}"    

    def get_delete_absolute_url(self):
        """Return absolute url of delete subject by its id.""" 
        return reverse('weather:delete-summary', kwargs={'summary_id': self.pk})

weather/forms.py
from django import forms

from .models import Weather


class AddWeatherForm(forms.ModelForm):
    """
    Add weather record model form.
    """
    temp = forms.FloatField(
        label='Temperature', 
        widget=forms.NumberInput(attrs={
            'class':'form-control', 
            'name':'temperature', 
            'placeholder':"Temperature (from 19 to 28)",
            'step': 0.25,
            'min': 19,
            'max': 28,
            'required': True,
        })
    )
    humidity = forms.FloatField(
        label='Humidity', 
        widget=forms.NumberInput(attrs={
            'class':'form-control', 
            'name':'humidity', 
            'placeholder':"Humidity (from 35 to 65)",
            'step': 0.25,
            'min': 35,
            'max': 65,
            'required': True,
        })
    )

    class Meta:
        model  = Weather
        fields = ['temp', 'humidity']

weather/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib import messages
from django.template.loader import render_to_string
from django.views.generic import ListView

from .models import Weather, Summary
from .forms import AddWeatherForm


def add_weather(request):
    """
    Add new weather record.
    """
    if request.method == "POST":
        form = AddWeatherForm(request.POST)
        if form.is_valid():
            form.save()
            # Display success message.
            messages.success(request, f'New weather record has been added successfully.', extra_tags='add-weather')
            return redirect('weather:weather-list')
    else:
        form = AddWeatherForm()          
    context = {'form':form}
    return render(request, 'weather/add_weather.html', context)


def weather_list(request):
    """
    Display weather records list.
    """
    qs = Weather.objects.all()
    context = {'weather_records': qs}
    return render(request, 'weather/weather_list.html', context)


def summary_list(request):
    """
    Display summary records list.
    """
    qs = Summary.objects.all()
    context = {'summary_records': qs}
    return render(request, 'weather/summary_list.html', context)


def delete_summary(request, summary_id):
    """
    Take summary's id, and get its summary and delete it.
    """
    # get summary by its id. 
    summary = get_object_or_404(Summary, pk=summary_id)
    data = dict()
    if request.method == 'POST':
        # delete summary.
        summary.delete()
        data['form_is_valid'] = True
        qs = Summary.objects.all()
        context = {'summary_records': qs, 'request':request}
        data['html_summary_list'] = render_to_string('weather/includes/partial_summary_list.html', context, request=request)
    else:
        context = {'summary': summary}
        data['html_form'] = render_to_string('weather/includes/partial_summary_delete.html', context, request=request)
    return JsonResponse(data)    


# class WeatherListView(ListView):
#     """
#     """
#     model = Weather
#     context_object_name = 'weather_records'
#     template_name = 'weather/weather_list.html'


templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}

    {% endblock title %}
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <!-- Custom Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    
    
</head>

{% include 'navbar.html' %}
{% block content %}

{% endblock content %}

</html>

templates/navbar.html
{% url 'weather:add-weather' as add_weather %} 
{% url 'weather:weather-list' as weather_list %}
{% url 'weather:summary-list' as summary_list %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand font-weight-600" href="#">Abu Erdan</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == weather_list %} active {% endif %}">
          <a class="nav-link" href="{% url 'weather:weather-list' %}">Weather</a>
        </li>
        <li class="nav-item {% if request.path == add_weather %} active {% endif %}">
          <a class="nav-link" href="{% url 'weather:add-weather' %}">Add Weather</a>
        </li>
        <li class="nav-item {% if request.path == summary_list %} active {% endif %}">
          <a class="nav-link" href="{% url 'weather:summary-list' %}">Summary</a>
        </li>
      </ul>
    </div>
  </nav>

templates/weather/add_weather.html
{% extends 'base.html' %}

{% block title %}
<title>Add Weather</title>
{% endblock title %}

{% block content %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper py-4">
            <!-- Content Header (Page header) -->
            <div class="content-header mb-4">
                <div class="container-fluid">
                    <h1 class="m-0 text-dark">Add Weather</h1>
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Add a new record</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action='.' method='POST'>
                                    {% csrf_token %}
                                    <div class="card-body">
                                        {{ form }}
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer d-flex justify-content-end">
                                        <button type="submit" name='save' class="btn btn-primary">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- ./wrapper -->

    <!-- scripts -->
    

</body>

{% endblock content %}

templates/weather/includes/partial_summary_delete.html
<!-- form start -->
<form role="form" action='{{ summary.get_delete_absolute_url }}' method='POST' class="js-summary-delete-form">
    {% csrf_token %}
    <!-- modal header -->
    <div class="modal-header">
        <h4 class="modal-title">Delete Summary</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <!-- modal body -->
    <div class="modal-body">
        <p class="lead">Are you sure you want to delete this summary?</p>
    </div>
    <!-- modal footer -->
    <div class="modal-footer justify-content-between">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete</button>
    </div>
</form>

templates/weather/includes/partial_summary_list.html
{% for obj in summary_records %}
<tr>
    <td class='text-center'>{{ forloop.counter }}</td>
    <td class='text-center'>{{ obj.start_date }}</td>
    <td class='text-center'>{{ obj.end_date }}</td>
    <td class='text-center'>{{ obj.avg_temp }}</td>
    <td class='text-center'>{{ obj.avg_humidity }}</td>
    <td class='text-center'>
        <div class="btn-group btn-group-sm">
            <button type="button" class="btn btn-danger js-delete-summary"
                data-url="{{ obj.get_delete_absolute_url }}">
                <i class="fas fa-trash"></i>
            </button>
        </div>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="6" class="text-center bg-warning"><b>No Records</b></td>
</tr>
{% endfor %}

templates/weather/includes/partial_weather_list.html
{% for obj in weather_records %}
<tr>
    <td class='text-center'>{{ forloop.counter }}</td>
    <td class='text-center'>{{ obj.date }}</td>
    <td class='text-center'>{{ obj.time }}</td>
    <td class='text-center
    {% if obj.is_temp_gt_25 %} 
        text-danger 
    {% elif obj.is_temp_lte_25 %} 
        text-success
    {% endif %}'>
        <div class="d-flex align-items-center justify-content-center">
            <span class="mr-3">{{ obj.temp }}</span>
            {% if obj.is_temp_lt_prev %}
            <i class="fa fa-arrow-down text-success"></i>
            {% elif obj.is_temp_gt_prev %}
            <i class="fa fa-arrow-up text-danger"></i>
            {% endif %}
        </div>
    </td>
    <td class='text-center
    {% if obj.is_humidity_gt_55 %} 
        text-danger 
    {% elif obj.is_humidity_lte_55 %} 
        text-success
    {% endif %}'>
        <div class="d-flex align-items-center justify-content-center">
            <span class="mr-3">{{ obj.humidity }}</span>
            {% if obj.is_humidity_lt_prev %}
            <i class="fa fa-arrow-down text-success"></i>
            {% elif obj.is_humidity_gt_prev %}
            <i class="fa fa-arrow-up text-danger"></i>
            {% endif %}
        </div>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="5" class="text-center bg-warning"><b>No Records</b></td>
</tr>
{% endfor %}


{% ifchanged obj.temp %}
{% endifchanged %}

templates/weather/summary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Summary</title>
{% endblock title %}

{% block content %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper py-4">
            <!-- Content Header (Page header) -->
            <div class="content-header mb-4">
                <div class="container-fluid">
                    <h1 class="m-0 text-dark">Summary</h1>
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <!-- Main content -->
            <section>
                <div class="table-wrapper">
                    <table class="table-content" id='summary-table'>
                        <thead>
                            <tr>
                                <th class='text-center'>#</th>
                                <th class='text-center'>Start Date</th>
                                <th class='text-center'>End Date</th>
                                <th class='text-center'>Avg Temperature</th>
                                <th class='text-center'>Avg Humidity</th>
                                <th class='text-center'>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% include 'weather/includes/partial_summary_list.html' %}
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
        <!-- /.content-wrapper -->
        <!-- Summary Modal -->
        <div class="modal fade" id="modal-summary">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </div>
    <!-- ./wrapper -->

    <!-- scripts -->
    <script src="{% static 'js/weather/base.js' %}"></script>
    <script src="{% static 'js/weather/summary_list.js' %}"></script>
    
</body>

{% endblock content %}

templates/weather/weather_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Weather</title>
{% endblock title %}

{% block content %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper py-4">
            <!-- Content Header (Page header) -->
            <div class="content-header mb-4">
                <div class="container-fluid">
                    <h1 class="m-0 text-dark">Weather</h1>
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section>
                <div class="table-wrapper">
                    <!-- Display success message -->
                    {% if messages %}
                        {% for message in messages %}
                            {% if 'add-weather' in message.tags %}
                                <div class='alert alert-success message mt-2 mx-2'>{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}  
                    <table class="table-content" id='weather-table'>
                        <thead>
                            <tr>
                                <th class='text-center'>#</th>
                                <th class='text-center'>Date</th>
                                <th class='text-center'>Time</th>
                                <th class='text-center'>Temperature</th>
                                <th class='text-center'>Humidity</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% include 'weather/includes/partial_weather_list.html' %}
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->

    <!-- scripts -->
    <script src="{% static 'js/weather/base.js' %}"></script>
    
</body>

{% endblock content %}